version: "3.5"
services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: 'share-plus'
    ports:
      - "3005:3005"
      - "9999:9999"
    environment:
      DATA_BASE_NAME: share_plus
      DATA_BASE_URL: jdbc:postgresql://postgres:5432
      DATA_BASE_USER: postgres
      DATA_BASE_PASS: postgres      
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: share_plus
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/data/db

volumes:
  postgres-data:
