server:
  port: 9999
  address: 0.0.0.0
  servlet:
    context-path: /
api-prefix: ''
database-name: share_plus
spring:
  application:
    name: Share Plus
  datasource:
    url: jdbc:postgresql://192.168.49.1:5432/${database-name}
    username: postgres
    password: postgres
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/${database-name}
    user: postgres
    password: postgres
    default-schema: share_plus
    placeholder-replacement: false
    out-of-order: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

security:
  jwt:
    secret-key: 5bd40f8b9e9e197cccb9e62316128f7e3b94a0bd1e1e4ac2e295ee0dda3da2c6
    expiration-time: 36000000

logging:
  level:
    root: info
  file:
    name: share-plus.log
    path: /var/log/share-plus

brapi:
  url: https://brapi.dev/api
  token: 6ycfFdTeCR7YtmsQHhnU9G